#!/bin/bash
make_path="${PWD}"
compile_path="${make_path}/compile-kernel"
out_kernel="${compile_path}/output"
kernel_path=$1

cd ${make_path}
git clone https://github.com/morrownr/8821cu-20210118.git

mkdir rtl8 && cd uwe5621ds
wget https://raw.githubusercontent.com/armbian/build/master/patch/misc/wireless-driver-for-uwe5622-allwinner-bt-fix.patch
wget https://raw.githubusercontent.com/armbian/build/master/patch/misc/wireless-driver-for-uwe5622-allwinner-bugfix.patch
wget https://raw.githubusercontent.com/armbian/build/master/patch/misc/wireless-driver-for-uwe5622-allwinner.patch

cd ${kernel_path}
patch -p1 < ${make_path}/uwe5621ds/wireless-driver-for-uwe5622-allwinner.patch
patch -p1 < ${make_path}/uwe5621ds/wireless-driver-for-uwe5622-allwinner-bugfix.patch

sed -i "s/default n/default y/g" drivers/net/wireless/uwe5622/Kconfig
sed -i "/Sprd UWE5621 Wi-Fi Driver./a\        default m"  drivers/net/wireless/uwe5622/unisocwifi/Kconfig
sed -i "/ti\//a obj-\$(CONFIG_SPARD_WLAN_SUPPORT) +=  uwe5622/" drivers/net/wireless/Makefile

make oldconfig && make prepare
echo -e "check config"
cp .config ${out_kernel}/config.tar.gz
cat .config |grep "UWE"

make KDIR=${kernel_path} M=drivers/net/wireless/uwe5622 modules

#arch_info="$(arch)"
#drivers_repo="KryptonLee/uwe5621ds-aml"
#git clone -q --single-branch --depth 1 https://github.com/${drivers_repo}
#cd uwe5621ds-aml/unisocwifi
#mkdir build
#make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KDIR="${kernel_path}" SRC_PATH="${PWD}" M="${PWD}" all
mkdir -p drivers/net/wireless/uwe5622/build
cd drivers/net/wireless/uwe5622; find -name "*.ko" -exec cp {} ./build/ \;
tar zcf ${out_kernel}/uwe5621.tar.gz ./build/*
