#!/bin/bash
make_path="${PWD}"
compile_path="${make_path}/compile-kernel"
out_kernel="${compile_path}/output"
kernel_path=$1

cd ${kernel_path}
make oldconfig && make prepare

cd ${make_path}
#arch_info="$(arch)"
drivers_repo="KryptonLee/uwe5621ds-aml"
git clone -q --single-branch --depth 1 https://github.com/${drivers_repo}
cd uwe5621ds-aml
mkdir build
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KDIR="${kernel_path}" M="${PWD}" all
cd ${make_path}/uwe5621ds-aml; find -name "*.ko" -exec cp {} build/ \;
tar zcf ${out_kernel}/uwe5621ds.tar.gz build/*
